### ISSUE TITLE
数据存储

### ISSUE THREAD

**Issue by YizhouXu-hkbu** [WANGKai-KaiXin/B-Tree#1]
你们对B-tree的数据存储有什么想法吗，是写一个node object用来存储，还是用一个array层层镶套，还是两个结合起来，一层层的node object互相镶套

**Comment by WANGKai-KaiXin** [comment]
我觉着可以用Node来储存二叉树，然后arraylist用来实现Alternative2的数据储存

YizhouXu-hkbu ***@***.***>于2021年11月28日 周日14:41写道：

**Comment by YizhouXu-hkbu** [comment]
我看了一下要求 “For simplicity, we only handle integer search keys; we don’t maintain actual data records (so the rids in data entries can be set to null).”，也就是说虽然采用了alternative2，但其实不用考虑数据存储。只需要用node来构建整棵树就行了

**Comment by WANGKai-KaiXin** [comment]
那可以的呀，就更简单了感觉

YizhouXu-hkbu ***@***.***>于2021年11月29日 周一17:43写道：
