### ISSUE TITLE
初始化

### ISSUE THREAD

**Issue by YizhouXu-hkbu** [WANGKai-KaiXin/B-Tree#2]
int[] key = new int[2 * T - 1];
Node[] child = new Node[2 * T];

这里的数量关系确实是这样的，不过应该是2*T个key和2*T-1个child吧，不然就成了奇数个key和偶数个entries了

**Comment by WANGKai-KaiXin** [comment]
哦对，child应该是奇数个，key是偶数个

YizhouXu-hkbu ***@***.***>于2021年11月29日 周一18:21写道：

**Comment by YizhouXu-hkbu** [comment]
行，那我帮你改了
